version: "3"
services:
  postgres:
    image: postgres
    container_name: okazudb
    ports:
      - "5555:5432"
    environment:
      - "POSTGRES_USER=root"
      - "POSTGRES_PASSWORD=password"
    tty: true
    restart: always
    user: root
    volumes:
      - ./init:/docker-entrypoint-initdb.d

  pgweb:
    image: sosedoff/pgweb
    container_name: pgweb
    ports:
      - "8081:8081"
    environment:
      - DATABASE_URL=postgres://root:password@postgres:5432/okazudb?sslmode=disable
    links:
      - postgres:postgres
    restart: always
    depends_on:
      - postgres
